[project]
name = "infiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.24.0",
    "jupyter>=1.1.1",
    "mcp[cli]>=1.13.0",
    "openai>=1.100.0",
    "pandas>=2.3.1",
]
